# Generated by Django 4.1.4 on 2023-02-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KRISHIBHAVAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("place", models.CharField(max_length=30)),
                ("municipality", models.CharField(max_length=40)),
                ("panchayath", models.CharField(max_length=40)),
                ("district", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=30)),
                ("pin_code", models.DecimalField(decimal_places=0, max_digits=6)),
                ("phone", models.CharField(max_length=14)),
                ("email", models.EmailField(max_length=254)),
                ("ecode", models.CharField(max_length=6)),
            ],
        ),
    ]
