# Generated by Django 4.1.4 on 2023-02-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KISAN_APP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="krishibhavan",
            name="ecode",
            field=models.CharField(max_length=8),
        ),
    ]
