# Generated by Django 4.1.4 on 2023-02-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KISAN_APP", "0003_krishibhavan_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ONLINE_SERVICES",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ecode", models.CharField(max_length=8)),
                ("ServiceName", models.CharField(max_length=200)),
                ("Description", models.CharField(max_length=200)),
                ("Scheme", models.CharField(max_length=200)),
                ("Eligibility", models.CharField(max_length=200)),
                ("How_To_Apply", models.CharField(max_length=200)),
                ("Whom_To_Contact", models.CharField(max_length=200)),
                ("URL", models.CharField(max_length=200)),
                ("Last_Date", models.DateField()),
            ],
        ),
    ]
