# Generated by Django 4.1.4 on 2023-02-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KISAN_APP", "0005_online_services_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SCHEME_APPLICATIONS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=8)),
                ("Name", models.CharField(max_length=40)),
                ("Aadhar_No", models.CharField(max_length=12)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone", models.CharField(max_length=14)),
                ("Village", models.CharField(max_length=40)),
                ("Panchayath", models.CharField(max_length=40)),
                ("District", models.CharField(max_length=40)),
                ("is_KisanCard", models.IntegerField()),
            ],
        ),
    ]
