# Generated by Django 4.1.4 on 2023-02-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KISAN_APP", "0006_scheme_applications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme_applications",
            name="is_KisanCard",
            field=models.IntegerField(max_length=1),
        ),
    ]
