# Generated by Django 4.1.4 on 2023-02-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KISAN_APP", "0007_alter_scheme_applications_is_kisancard"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme_applications",
            name="Scheme_id",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheme_applications",
            name="pin_code",
            field=models.IntegerField(default=123456, max_length=6),
            preserve_default=False,
        ),
    ]
