# Generated by Django 4.1.4 on 2023-02-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KISAN_APP", "0008_scheme_applications_scheme_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme_applications",
            name="is_KisanCard",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="scheme_applications",
            name="pin_code",
            field=models.IntegerField(),
        ),
    ]
