# Generated by Django 4.1.4 on 2023-02-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("KISAN_APP", "0010_user_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_notifications",
            name="text",
            field=models.CharField(max_length=40),
        ),
    ]
