# Generated by Django 4.1.4 on 2023-02-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("KISAN_APP", "0011_alter_user_notifications_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_notifications", old_name="user", new_name="user_id",
        ),
    ]
